(cl:defpackage lab2-msg
  (:use )
  (:export
   "<NAVTARGETACTION>"
   "NAVTARGETACTION"
   "<NAVTARGETACTIONFEEDBACK>"
   "NAVTARGETACTIONFEEDBACK"
   "<NAVTARGETACTIONGOAL>"
   "NAVTARGETACTIONGOAL"
   "<NAVTARGETACTIONRESULT>"
   "NAVTARGETACTIONRESULT"
   "<NAVTARGETFEEDBACK>"
   "NAVTARGETFEEDBACK"
   "<NAVTARGETGOAL>"
   "NAVTARGETGOAL"
   "<NAVTARGETRESULT>"
   "NAVTARGETRESULT"
  ))

