; Auto-generated. Do not edit!


(cl:in-package lab2-msg)


;//! \htmlinclude NavTargetResult.msg.html

(cl:defclass <NavTargetResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool)))
)

(cl:defclass NavTargetResult (<NavTargetResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavTargetResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavTargetResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab2-msg:<NavTargetResult> is deprecated: use lab2-msg:NavTargetResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <NavTargetResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab2-msg:success-val is deprecated.  Use lab2-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavTargetResult>) ostream)
  "Serializes a message object of type '<NavTargetResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'success) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavTargetResult>) istream)
  "Deserializes a message object of type '<NavTargetResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'success) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavTargetResult>)))
  "Returns string type for a message object of type '<NavTargetResult>"
  "lab2/NavTargetResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavTargetResult)))
  "Returns string type for a message object of type 'NavTargetResult"
  "lab2/NavTargetResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavTargetResult>)))
  "Returns md5sum for a message object of type '<NavTargetResult>"
  "5f31cb2e813cfb0e488c574c3b5d9dbe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavTargetResult)))
  "Returns md5sum for a message object of type 'NavTargetResult"
  "5f31cb2e813cfb0e488c574c3b5d9dbe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavTargetResult>)))
  "Returns full string definition for message of type '<NavTargetResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Bool success~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavTargetResult)))
  "Returns full string definition for message of type 'NavTargetResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%std_msgs/Bool success~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavTargetResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'success))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavTargetResult>))
  "Converts a ROS message object to a list"
  (cl:list 'NavTargetResult
    (cl:cons ':success (success msg))
))
