; Auto-generated. Do not edit!


(cl:in-package lab2-msg)


;//! \htmlinclude NavTargetGoal.msg.html

(cl:defclass <NavTargetGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type geometry_msgs-msg:PointStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PointStamped)))
)

(cl:defclass NavTargetGoal (<NavTargetGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavTargetGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavTargetGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab2-msg:<NavTargetGoal> is deprecated: use lab2-msg:NavTargetGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <NavTargetGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab2-msg:goal-val is deprecated.  Use lab2-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavTargetGoal>) ostream)
  "Serializes a message object of type '<NavTargetGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavTargetGoal>) istream)
  "Deserializes a message object of type '<NavTargetGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavTargetGoal>)))
  "Returns string type for a message object of type '<NavTargetGoal>"
  "lab2/NavTargetGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavTargetGoal)))
  "Returns string type for a message object of type 'NavTargetGoal"
  "lab2/NavTargetGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavTargetGoal>)))
  "Returns md5sum for a message object of type '<NavTargetGoal>"
  "e88395c1654d49c84d945905e3bcde8e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavTargetGoal)))
  "Returns md5sum for a message object of type 'NavTargetGoal"
  "e88395c1654d49c84d945905e3bcde8e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavTargetGoal>)))
  "Returns full string definition for message of type '<NavTargetGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PointStamped goal~%~%================================================================================~%MSG: geometry_msgs/PointStamped~%# This represents a Point with reference coordinate frame and timestamp~%Header header~%Point point~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavTargetGoal)))
  "Returns full string definition for message of type 'NavTargetGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PointStamped goal~%~%================================================================================~%MSG: geometry_msgs/PointStamped~%# This represents a Point with reference coordinate frame and timestamp~%Header header~%Point point~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavTargetGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavTargetGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'NavTargetGoal
    (cl:cons ':goal (goal msg))
))
