// Generated by gencpp from file lab2/NavTargetGoal.msg
// DO NOT EDIT!


#ifndef LAB2_MESSAGE_NAVTARGETGOAL_H
#define LAB2_MESSAGE_NAVTARGETGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>

namespace lab2
{
template <class ContainerAllocator>
struct NavTargetGoal_
{
  typedef NavTargetGoal_<ContainerAllocator> Type;

  NavTargetGoal_()
    : goal()  {
    }
  NavTargetGoal_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::lab2::NavTargetGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab2::NavTargetGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavTargetGoal_

typedef ::lab2::NavTargetGoal_<std::allocator<void> > NavTargetGoal;

typedef boost::shared_ptr< ::lab2::NavTargetGoal > NavTargetGoalPtr;
typedef boost::shared_ptr< ::lab2::NavTargetGoal const> NavTargetGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab2::NavTargetGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab2::NavTargetGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab2::NavTargetGoal_<ContainerAllocator1> & lhs, const ::lab2::NavTargetGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab2::NavTargetGoal_<ContainerAllocator1> & lhs, const ::lab2::NavTargetGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab2::NavTargetGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2::NavTargetGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2::NavTargetGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2::NavTargetGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2::NavTargetGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2::NavTargetGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab2::NavTargetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e88395c1654d49c84d945905e3bcde8e";
  }

  static const char* value(const ::lab2::NavTargetGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe88395c1654d49c8ULL;
  static const uint64_t static_value2 = 0x4d945905e3bcde8eULL;
};

template<class ContainerAllocator>
struct DataType< ::lab2::NavTargetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab2/NavTargetGoal";
  }

  static const char* value(const ::lab2::NavTargetGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab2::NavTargetGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PointStamped goal\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::lab2::NavTargetGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab2::NavTargetGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavTargetGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab2::NavTargetGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab2::NavTargetGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB2_MESSAGE_NAVTARGETGOAL_H
