// Generated by gencpp from file lab2/NavTargetFeedback.msg
// DO NOT EDIT!


#ifndef LAB2_MESSAGE_NAVTARGETFEEDBACK_H
#define LAB2_MESSAGE_NAVTARGETFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>

namespace lab2
{
template <class ContainerAllocator>
struct NavTargetFeedback_
{
  typedef NavTargetFeedback_<ContainerAllocator> Type;

  NavTargetFeedback_()
    : distance()  {
    }
  NavTargetFeedback_(const ContainerAllocator& _alloc)
    : distance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::lab2::NavTargetFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab2::NavTargetFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct NavTargetFeedback_

typedef ::lab2::NavTargetFeedback_<std::allocator<void> > NavTargetFeedback;

typedef boost::shared_ptr< ::lab2::NavTargetFeedback > NavTargetFeedbackPtr;
typedef boost::shared_ptr< ::lab2::NavTargetFeedback const> NavTargetFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab2::NavTargetFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab2::NavTargetFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab2::NavTargetFeedback_<ContainerAllocator1> & lhs, const ::lab2::NavTargetFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab2::NavTargetFeedback_<ContainerAllocator1> & lhs, const ::lab2::NavTargetFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab2::NavTargetFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab2::NavTargetFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2::NavTargetFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab2::NavTargetFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2::NavTargetFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab2::NavTargetFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab2::NavTargetFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1093a895d389825abe211cea01772a0";
  }

  static const char* value(const ::lab2::NavTargetFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1093a895d389825ULL;
  static const uint64_t static_value2 = 0xabe211cea01772a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab2::NavTargetFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab2/NavTargetFeedback";
  }

  static const char* value(const ::lab2::NavTargetFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab2::NavTargetFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"std_msgs/Float32 distance\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::lab2::NavTargetFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab2::NavTargetFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavTargetFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab2::NavTargetFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab2::NavTargetFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB2_MESSAGE_NAVTARGETFEEDBACK_H
